MA.unit({
  id: 'u1', title: 'Fondamentaux du M&A', icon: '🤝',
  desc: 'Types d’opérations, acteurs, motivations, cadre français',
  lessons: [
    {
      id: 'u1l1', title: 'Les types d’opérations',
      cards: [
        ['Fusion vs acquisition', `Une <b>acquisition</b> : une société (l'acquéreur) prend le contrôle d'une autre (la cible). Une <b>fusion</b> : deux entités se combinent en une seule, souvent entre sociétés de taille comparable (« merger of equals »).<br><br>En pratique, la quasi-totalité des deals sont des acquisitions, même quand on les présente comme des fusions.`],
        ['Horizontal, vertical, conglomérat', `<ul><li><b>Horizontale</b> : même métier, même niveau de la chaîne de valeur (deux cimentiers). Objectif : taille, parts de marché, synergies de coûts.</li><li><b>Verticale</b> : amont ou aval (un constructeur rachète un fournisseur). Objectif : sécuriser l'approvisionnement, capter la marge.</li><li><b>Conglomérale</b> : activités sans lien. Objectif : diversification. Souvent sanctionnée par une décote de conglomérat.</li></ul>`],
        ['Opérations de LBO', `<ul><li><b>LBO</b> (Leveraged Buy-Out) : un fonds rachète une société en finançant une large part avec de la dette, remboursée par les cash-flows de la cible.</li><li><b>MBO</b> : le management en place rachète avec un fonds.</li><li><b>MBI</b> : une équipe de management externe entre.</li><li><b>OBO</b> : le dirigeant-actionnaire revend à une holding qu'il contrôle avec un fonds, pour sécuriser une partie de son patrimoine.</li><li><b>Secondary / tertiary LBO</b> : un fonds revend à un autre fonds.</li></ul>`],
        ['Cessions et séparations', `<ul><li><b>Carve-out</b> : cession d'une division (ou introduction en bourse d'une partie de celle-ci).</li><li><b>Spin-off</b> : la division est distribuée aux actionnaires existants, qui reçoivent des titres de la nouvelle entité. Pas de cash pour la maison mère.</li><li><b>Joint-venture</b> : deux partenaires créent une entité commune.</li></ul>`],
        ['Share deal vs asset deal', `<b>Share deal</b> : on achète les titres → on récupère la société avec tout son historique (passif caché compris). Simple, transfert automatique des contrats.<br><br><b>Asset deal</b> : on achète des actifs choisis (fonds de commerce, brevets, usine). L'acheteur choisit ce qu'il reprend, mais les contrats doivent souvent être transférés un par un et la fiscalité diffère (droits d'enregistrement).`]
      ],
      qs: [
        mcq('Un constructeur automobile rachète son fournisseur de batteries. Type d’opération ?', ['Horizontale', 'Verticale', 'Conglomérale', 'Spin-off'], 1, 'Le fournisseur est en amont dans la chaîne de valeur : intégration verticale.'),
        mcq('Le dirigeant actionnaire majoritaire revend sa société à une holding qu’il contrôle avec un fonds. C’est un :', ['MBI', 'OBO', 'Spin-off', 'Carve-out'], 1, 'OBO (Owner Buy-Out) : le dirigeant « se revend » sa société pour encaisser une partie de la valeur tout en gardant le contrôle.'),
        tf('Dans un spin-off, la maison mère reçoit du cash de la part d’un acquéreur.', false, 'Dans un spin-off, les titres de la filiale sont distribués aux actionnaires existants : aucun cash n’est encaissé. C’est la différence avec une cession (carve-out).'),
        mcq('Dans un share deal, l’acheteur :', ['Choisit les actifs qu’il reprend', 'Reprend la société avec l’ensemble de ses passifs, y compris cachés', 'N’est jamais exposé au passé fiscal de la cible', 'Doit renégocier chaque contrat'], 1, 'L’acheteur reprend la personne morale entière, d’où l’importance de la due diligence et des garanties (GAP / indemnities) dans le SPA.'),
        mcq('Une équipe de managers externes entre au capital avec un fonds pour diriger la cible. C’est un :', ['MBO', 'MBI', 'OBO', 'BIMBO'], 1, 'MBI = Management Buy-In (management externe). MBO = management en place. BIMBO = combinaison des deux.'),
        tf('Une opération conglomérale vise principalement des synergies de coûts.', false, 'Sans lien entre les métiers, les synergies sont faibles. La logique est la diversification, et le marché applique souvent une décote de conglomérat.'),
        mcq('Quel avantage principal de l’asset deal pour l’acheteur ?', ['Transfert automatique des contrats', 'Choisir les actifs et laisser les passifs', 'Fiscalité toujours plus favorable', 'Process plus rapide'], 1, 'L’acheteur sélectionne ce qu’il reprend, ce qui limite le risque de passifs cachés. En contrepartie, le transfert des contrats est plus lourd.'),
        open('Quelle est la différence entre un share deal et un asset deal ? Quand privilégier l’un ou l’autre ?', 'Share deal : achat des titres, on reprend la société entière avec son historique (actifs, passifs, contrats, risques). Simple et rapide, les contrats suivent automatiquement (sauf clauses de changement de contrôle). Asset deal : achat d’actifs sélectionnés ; l’acheteur évite les passifs non désirés mais doit transférer contrats et salariés et supporte des droits d’enregistrement plus élevés. On privilégie l’asset deal pour une division non filialisée, une société en difficulté (risques de passif) ou quand on ne veut qu’une partie de l’activité.', ['Share deal = titres, reprise du passif', 'Asset deal = sélection des actifs', 'Transfert des contrats (automatique vs un par un)', 'Différence de fiscalité / droits d’enregistrement', 'Cas d’usage : division non filialisée, société en difficulté']),
      ]
    },
    {
      id: 'u1l2', title: 'Les acteurs d’un deal',
      cards: [
        ['Les clients', `<ul><li><b>Corporates / stratégiques</b> : industriels qui achètent pour des raisons stratégiques. Ils peuvent payer les synergies.</li><li><b>Sponsors financiers (fonds de PE)</b> : achètent pour revendre 4 à 7 ans plus tard avec un TRI cible (souvent 20 %+). Utilisent le levier de la dette.</li><li><b>Family offices, fonds souverains, infrastructure</b> : horizon plus long, rendements plus faibles acceptés.</li></ul>`],
        ['Les conseils', `<ul><li><b>Banque d'affaires / conseil M&A</b> : pilote le process, valorise, négocie. Bulge brackets (grandes banques internationales), banques françaises, boutiques indépendantes (Rothschild & Co, Lazard…), mid-cap.</li><li><b>Avocats</b> : structuration juridique, SPA, due diligence juridique.</li><li><b>Transaction Services</b> (Big 4 et autres) : due diligence financière, quality of earnings, dette nette, BFR normatif.</li><li><b>Conseils en stratégie</b> : due diligence de marché (commercial DD).</li></ul>`],
        ['Côté financement', `<ul><li><b>Leveraged finance</b> des banques et <b>fonds de dette privée</b> (unitranche) financent les LBO.</li><li><b>ECM</b> intervient si le financement passe par une augmentation de capital.</li><li><b>DCM</b> pour les émissions obligataires d'acquisition.</li></ul>`],
        ['Ce que fait un analyste M&A', `Modélisation (DCF, LBO, accretion/dilution), comps et précédents, rédaction du teaser et de l'IM, préparation des présentations clients (pitchs), gestion de la data room, coordination avec les conseils et suivi des Q&A. Beaucoup d'Excel, de PowerPoint et de rigueur.`],
        ['Sell-side vs buy-side', `<b>Sell-side</b> : on conseille le vendeur, on organise le process (souvent des enchères) pour maximiser le prix et la sécurité de l'exécution.<br><b>Buy-side</b> : on conseille l'acheteur, on identifie les cibles, on valorise et on structure l'offre.<br>Le sell-side représente l'essentiel du travail d'exécution d'un analyste.`]
      ],
      qs: [
        mcq('Qui réalise typiquement la due diligence financière (quality of earnings, dette nette) ?', ['La banque d’affaires', 'Les avocats', 'Les équipes Transaction Services', 'L’AMF'], 2, 'Les équipes TS (Big 4 notamment) réalisent la DD financière : retraitements de l’EBITDA, dette nette, BFR normatif.'),
        tf('Un acquéreur stratégique peut généralement payer plus cher qu’un fonds de PE, toutes choses égales par ailleurs.', true, 'Il peut intégrer une partie de la valeur des synergies dans son prix, alors que le fonds est contraint par son TRI cible et sa capacité d’endettement.'),
        mcq('Horizon de détention typique d’un fonds de LBO :', ['6 à 12 mois', '4 à 7 ans', '15 à 20 ans', 'Indéfini'], 1, 'Les fonds de PE ont une durée de vie limitée (~10 ans) et revendent leurs participations généralement entre 4 et 7 ans.'),
        mcq('Quelle équipe d’une banque gère le financement par dette d’un LBO ?', ['ECM', 'Leveraged finance', 'Sales & Trading', 'Equity research'], 1, 'Le leveraged finance (ou acquisition finance) structure et arrange la dette d’acquisition. Les fonds de dette privée sont des concurrents directs, via l’unitranche.'),
        mcq('En mandat sell-side, l’objectif principal du conseil est :', ['Trouver la cible idéale', 'Maximiser le prix et la sécurité d’exécution pour le vendeur', 'Structurer la dette de l’acheteur', 'Rédiger les comptes annuels'], 1, 'Le conseil sell-side crée de la tension concurrentielle (enchères) et sécurise la transaction pour le vendeur.'),
        tf('La commercial due diligence est généralement confiée à un cabinet de conseil en stratégie.', true, 'Elle valide le business plan : taille du marché, croissance, position concurrentielle.'),
        open('Que fait concrètement un analyste en M&A au quotidien ?', 'Modélisation financière (DCF, LBO, accretion/dilution, comps et transactions précédentes), préparation des supports : pitchs, teaser, information memorandum, présentation management. Gestion de la data room et du suivi des Q&A, coordination avec les conseils (avocats, TS) et les acheteurs. Beaucoup de recherche sectorielle et de rigueur sur les chiffres. Il est le premier rempart contre les erreurs et doit maîtriser Excel et PowerPoint.', ['Modélisation (DCF, LBO, comps)', 'Supports : pitch, teaser, IM', 'Data room et Q&A', 'Coordination avec les conseils', 'Rigueur, rôle de contrôle qualité']),
      ]
    },
    {
      id: 'u1l3', title: 'Pourquoi faire une acquisition ?',
      cards: [
        ['Les motivations', `<ul><li><b>Croissance externe</b> : plus rapide que la croissance organique.</li><li><b>Synergies</b> : de coûts ou de revenus.</li><li><b>Nouveaux marchés</b> : géographies, clients, produits.</li><li><b>Technologie et talents</b> (acqui-hire).</li><li><b>Consolidation</b> d'un marché fragmenté (buy-and-build).</li><li><b>Pouvoir de marché</b> vis-à-vis des clients et fournisseurs.</li></ul>`],
        ['Les synergies', `<b>Synergies de coûts</b> : suppression des doublons (sièges, IT), achats groupés, rationalisation industrielle. Elles sont plus <b>crédibles</b> car elles dépendent de l'acheteur.<br><br><b>Synergies de revenus</b> : ventes croisées, accès à de nouveaux canaux. Plus <b>incertaines</b>, car elles dépendent des clients. Le marché les décote fortement.<br><br>Toujours intégrer les <b>coûts de mise en œuvre</b> (restructuration, IT, départs).`],
        ['La prime de contrôle', `Pour acquérir le contrôle d'une société cotée, l'acheteur paie une <b>prime</b> par rapport au cours de bourse, souvent de l'ordre de <b>20 à 40 %</b>. Elle rémunère l'accès aux flux de trésorerie et la possibilité d'en décider l'usage, et c'est la part des synergies que l'acheteur cède au vendeur.<br><br>Règle d'or : on ne doit pas payer en prime plus que la valeur actuelle nette des synergies, sinon on détruit de la valeur pour ses propres actionnaires.`],
        ['Pourquoi tant de deals échouent', `Prix trop élevé (« winner's curse »), synergies surestimées, intégration ratée (culture, systèmes, départ des talents), dette excessive, mauvaise due diligence. C'est une question d'entretien fréquente : citer 3 raisons structurées.`]
      ],
      qs: [
        mcq('Quel type de synergies le marché juge-t-il le plus crédible ?', ['Synergies de revenus', 'Synergies de coûts', 'Synergies fiscales', 'Synergies de marque'], 1, 'Les synergies de coûts dépendent des décisions de l’acheteur (fermeture de sites, achats groupés), alors que les synergies de revenus dépendent du comportement des clients.'),
        tf('Un acquéreur crée de la valeur pour ses actionnaires s’il paie une prime supérieure à la VAN des synergies.', false, 'Si la prime dépasse la valeur actuelle des synergies (nette des coûts de mise en œuvre), toute la valeur créée est transférée aux vendeurs, et au-delà.'),
        num('Une cible vaut 1 000 M€ en standalone. Synergies de coûts : 30 M€ par an après impôt, à perpétuité, actualisées à 10 %. Coûts de mise en œuvre : 50 M€. Prix maximum théorique à payer (M€) ?', 1250, 1, 'M€', 'VAN des synergies = 30 / 10 % − 50 = 250. Prix max = 1 000 + 250 = 1 250 M€ (à ce prix, toute la valeur des synergies va au vendeur).'),
        mcq('Fourchette souvent citée pour la prime de contrôle sur une société cotée :', ['0 à 5 %', '20 à 40 %', '80 à 100 %', 'Plus de 150 %'], 1, 'Les primes observées se situent généralement entre 20 et 40 %, avec de fortes variations selon le secteur et la situation concurrentielle.'),
        mcq('Le « winner’s curse » désigne :', ['Le fait de gagner un process en payant trop cher', 'Une clause anti-OPA', 'La perte d’un mandat', 'Une pénalité de rupture'], 0, 'Dans une enchère, celui qui gagne est souvent celui qui a le plus surestimé la valeur de la cible.'),
        ord('Classe ces synergies de la plus crédible à la moins crédible :', ['Suppression d’un siège en doublon', 'Économies sur les achats groupés', 'Ventes croisées aux clients de la cible', 'Création d’une nouvelle gamme commune'], 'Plus la synergie dépend de l’acheteur (coûts), plus elle est crédible ; plus elle dépend du marché (revenus, nouveaux produits), plus elle est incertaine.'),
        open('Pourquoi une entreprise ferait-elle une acquisition plutôt que de croître organiquement ?', 'Vitesse : acheter une position de marché va plus vite que la construire. Accès immédiat à des clients, une technologie, des talents, une géographie. Synergies de coûts et de revenus. Consolidation d’un marché fragmenté et pouvoir de négociation. Parfois défensif : empêcher un concurrent d’acheter. Limites : prime payée, risque d’intégration, dette.', ['Vitesse (time to market)', 'Accès clients / technologie / talents / géographie', 'Synergies', 'Consolidation, pouvoir de marché', 'Motif défensif', 'Mentionner les risques (prime, intégration)']),
        open('Pourquoi beaucoup d’acquisitions détruisent-elles de la valeur ?', 'Trois raisons principales. 1) Le prix : surenchère en process compétitif (winner’s curse), prime supérieure à la valeur des synergies. 2) L’exécution : synergies surestimées ou mal chiffrées, intégration ratée (systèmes, culture, départ des talents clés). 3) La structure : endettement excessif, due diligence insuffisante qui laisse passer des passifs. Biais de comportement aussi : ego des dirigeants, logique d’empire.', ['Prix trop élevé / winner’s curse', 'Synergies surestimées', 'Intégration (culture, systèmes, talents)', 'Dette excessive', 'Due diligence insuffisante']),
      ]
    },
    {
      id: 'u1l4', title: 'Le cadre français des offres publiques',
      cards: [
        ['OPA, OPE, OPR', `Sur une société cotée, l'acquisition passe par une <b>offre publique</b> contrôlée par l'<b>AMF</b> :<ul><li><b>OPA</b> : offre publique d'achat, paiement en cash.</li><li><b>OPE</b> : offre publique d'échange, paiement en titres de l'initiateur.</li><li><b>Offre mixte</b> : cash + titres.</li><li><b>OPR</b> : offre publique de retrait, préalable au retrait de la cote.</li></ul>`],
        ['Les seuils clés', `<ul><li><b>30 %</b> du capital ou des droits de vote : franchir ce seuil oblige à déposer une offre publique sur 100 % (offre obligatoire).</li><li><b>90 %</b> du capital et des droits de vote : permet un <b>retrait obligatoire</b> (squeeze-out) des minoritaires restants, seuil abaissé de 95 % à 90 % par la loi PACTE (2019).</li></ul>`],
        ['Amical ou hostile', `<b>Amicale</b> : recommandée par le conseil d'administration de la cible.<br><b>Hostile</b> : lancée sans l'accord du conseil.<br>Défenses possibles : chevalier blanc (white knight), bons d'émission d'actions (« bons Breton », l'équivalent français de la poison pill), contre-offre (Pac-Man), cession d'actifs convoités (crown jewels).`],
        ['Le rôle du CSE', `En France, le <b>CSE</b> (comité social et économique) doit être <b>informé et consulté</b> avant toute décision sur une cession. Conséquence pratique : on ne signe pas directement le SPA. L'acheteur remet une <b>promesse unilatérale d'achat</b> (put option) que le vendeur exerce après la consultation du CSE, puis on signe le SPA.`]
      ],
      qs: [
        num('À partir de quel pourcentage du capital ou des droits de vote faut-il déposer une offre publique obligatoire en France (%) ?', 30, 0, '%', 'Le franchissement du seuil de 30 % oblige à déposer une offre sur la totalité du capital.'),
        num('Seuil de détention permettant un retrait obligatoire (squeeze-out) en France depuis la loi PACTE (%) ?', 90, 0, '%', 'La loi PACTE (2019) a abaissé le seuil de 95 % à 90 % du capital et des droits de vote.'),
        mcq('Une offre publique rémunérée en titres de l’initiateur est une :', ['OPA', 'OPE', 'OPR', 'IPO'], 1, 'OPE = offre publique d’échange : les actionnaires de la cible reçoivent des titres de l’initiateur.'),
        mcq('Pourquoi signe-t-on souvent une promesse unilatérale d’achat avant le SPA en France ?', ['Pour des raisons fiscales', 'Parce que le CSE doit être consulté avant la décision de cession', 'Pour obtenir l’accord de l’AMF', 'Pour éviter la due diligence'], 1, 'La consultation du CSE doit précéder l’engagement définitif du vendeur. L’acheteur s’engage seul via une put option, le vendeur signe le SPA après.'),
        mcq('Quel est le régulateur des offres publiques en France ?', ['ACPR', 'AMF', 'Banque de France', 'Autorité de la concurrence'], 1, 'L’AMF contrôle les offres publiques. L’Autorité de la concurrence intervient sur le contrôle des concentrations.'),
        tf('Les « bons Breton » sont l’équivalent français de la poison pill.', true, 'Ce sont des bons de souscription d’actions émis en période d’offre pour renchérir le coût de l’opération pour l’initiateur hostile.'),
        mcq('Un « chevalier blanc » (white knight) est :', ['Un acquéreur hostile', 'Un acquéreur ami sollicité par la cible pour contrer une offre hostile', 'Un avocat de la cible', 'Le régulateur'], 1, 'La cible trouve un repreneur alternatif jugé plus favorable que l’initiateur hostile.'),
      ]
    }
  ]
});
