MA.unit({
  id: 'u2', title: 'Le process M&A', icon: '🗂️',
  desc: 'Enchères, documents, SPA, du signing au closing',
  lessons: [
    {
      id: 'u2l1', title: 'Le process d’enchères sell-side',
      cards: [
        ['Pourquoi des enchères ?', `Le vendeur met plusieurs acheteurs en <b>concurrence</b> pour maximiser le prix et les conditions. Variantes :<ul><li><b>Enchère large</b> : beaucoup d'acheteurs approchés, tension maximale, risque de fuite.</li><li><b>Enchère restreinte</b> : quelques acheteurs ciblés, plus confidentiel.</li><li><b>Négociation de gré à gré</b> : un seul acheteur, rapide et discret, mais peu de tension sur le prix.</li></ul>`],
        ['Phase 0 : préparation (4 à 8 semaines)', `Choix des conseils, <b>vendor due diligence</b> (VDD financière, juridique, parfois stratégique), business plan, rédaction du <b>teaser</b> et de l'<b>Information Memorandum</b>, longlist d'acheteurs, valorisation préliminaire.`],
        ['Phase 1 : offres indicatives', `Envoi du teaser (anonyme) → signature d'un <b>NDA</b> → envoi de l'IM et de la <b>process letter</b> → remise des <b>offres non engageantes</b> (NBO / IOI) avec une fourchette de prix et des hypothèses. Le vendeur sélectionne une shortlist.`],
        ['Phase 2 : offres fermes', `Accès à la <b>data room</b>, <b>management presentation</b>, visites de sites, sessions de Q&A, mark-up du projet de <b>SPA</b> fourni par le vendeur. Remise des <b>offres fermes</b> (binding offers) avec le financement sécurisé.`],
        ['Phase 3 : négociation et signature', `Le vendeur choisit le meilleur acheteur (prix, certitude, conditions), éventuellement avec une <b>exclusivité</b>. Finalisation du SPA → <b>signing</b>. Puis levée des conditions suspensives (concurrence, investissements étrangers…) → <b>closing</b> : transfert des titres et paiement du prix.`]
      ],
      qs: [
        ord('Remets les étapes d’un process d’enchères dans l’ordre :', ['Envoi du teaser', 'Signature du NDA', 'Envoi de l’IM et de la process letter', 'Offres non engageantes (NBO)', 'Data room et management presentation', 'Offres fermes', 'Signing du SPA', 'Closing']),
        mcq('Quel document est envoyé AVANT la signature du NDA ?', ['L’Information Memorandum', 'Le teaser', 'La data room', 'Le projet de SPA'], 1, 'Le teaser est anonyme et succinct : il suscite l’intérêt sans dévoiler d’information confidentielle. L’IM n’est partagé qu’après le NDA.'),
        mcq('Que reçoivent les acheteurs en phase 2 qu’ils n’ont pas en phase 1 ?', ['Le teaser', 'L’accès à la data room et au management', 'Le NDA', 'La longlist'], 1, 'La phase 2 permet une due diligence approfondie : data room, management presentation, visites, Q&A.'),
        tf('Une offre non engageante (NBO) oblige l’acheteur à acquérir au prix indiqué.', false, 'La NBO / IOI donne une fourchette indicative, sous réserve de due diligence. Seule l’offre ferme (binding) engage, et encore sous conditions suspensives.'),
        mcq('Avantage principal d’une négociation de gré à gré par rapport à une enchère ?', ['Prix plus élevé', 'Confidentialité et rapidité', 'Plus de tension concurrentielle', 'Moins de due diligence'], 1, 'Un seul interlocuteur : discret et rapide, mais sans tension sur le prix.'),
        mcq('Qu’est-ce qu’une vendor due diligence (VDD) ?', ['Une DD commandée par l’acheteur', 'Une DD commandée par le vendeur et partagée aux acheteurs', 'Un audit de l’AMF', 'L’audit des comptes annuels'], 1, 'La VDD est commandée par le vendeur avant le process. Elle accélère la DD acheteur et réduit les mauvaises surprises en fin de course.'),
        mcq('Durée typique d’un process d’enchères sell-side, de la préparation à la signature :', ['2 à 3 semaines', '4 à 6 mois', '2 à 3 ans', '1 semaine'], 1, 'Comptez environ 4 à 6 mois en moyenne, puis plusieurs semaines à mois jusqu’au closing selon les autorisations.'),
        open('Décris les grandes étapes d’un process de vente organisé par une banque d’affaires.', `Préparation : VDD, business plan, teaser, IM, longlist d'acheteurs et valorisation. Phase 1 : teaser, NDA, IM et process letter, offres indicatives non engageantes, sélection d'une shortlist. Phase 2 : data room, management presentation, Q&A, visites, mark-up du SPA, offres fermes avec financement. Négociation et choix de l'acquéreur (prix, certitude, conditions), exclusivité éventuelle, signing. Levée des conditions suspensives (concurrence, investissements étrangers, consultation du CSE en France) puis closing. Durée totale : environ 4 à 6 mois jusqu'au signing.`, ['Préparation (VDD, IM, teaser, longlist)', 'Phase 1 : NDA, IM, offres indicatives', 'Phase 2 : data room, management presentation, offres fermes', 'Négociation, signing', 'Conditions suspensives puis closing', 'Ordre de grandeur de durée']),
      ]
    },
    {
      id: 'u2l2', title: 'Les documents du deal',
      cards: [
        ['Teaser et NDA', `<b>Teaser</b> : 1 à 3 pages, anonyme, qui présente l'opportunité (activité, chiffres clés, points forts) sans nommer la cible.<br><br><b>NDA</b> (accord de confidentialité) : engagement à garder confidentiel ce qui est partagé, souvent avec une clause de <b>non-sollicitation</b> des salariés et parfois un <b>standstill</b> (interdiction d'acheter des titres en bourse).`],
        ['Information Memorandum', `L'<b>IM</b> (ou CIM) : document de 50 à 100 pages qui présente en détail la société, son marché, son modèle, son management, ses états financiers historiques et son business plan. C'est l'outil marketing principal du vendeur.`],
        ['Process letter', `Fixe les règles du jeu : calendrier, format des offres, éléments attendus (prix, structure, financement, conditions, due diligence restante), interlocuteurs autorisés.`],
        ['Data room et Q&A', `La <b>data room</b> (virtuelle) contient tous les documents de due diligence : contrats, statuts, contentieux, RH, fiscal, comptes détaillés. Les acheteurs posent leurs questions via un <b>Q&A log</b> que la banque coordonne.`],
        ['LOI et term sheet', `La <b>lettre d'intention</b> (LOI) et la <b>term sheet</b> résument les principaux termes négociés (prix, structure, exclusivité, conditions) avant la rédaction des contrats définitifs. Elles sont généralement non engageantes, sauf pour l'exclusivité et la confidentialité.`]
      ],
      qs: [
        mcq('Qu’est-ce qu’une clause de standstill dans un NDA ?', ['Interdiction de débaucher les salariés', 'Interdiction d’acheter des titres de la cible pendant une période', 'Obligation de faire une offre', 'Exclusivité de négociation'], 1, 'Le standstill empêche l’acheteur potentiel de ramasser des titres en bourse ou de lancer une offre hostile après avoir eu accès à l’information.'),
        mcq('Quel document fixe le calendrier et le format attendu des offres ?', ['Le teaser', 'La process letter', 'Le SPA', 'Le NDA'], 1, 'La process letter définit les règles : dates limites, contenu attendu des offres, interlocuteurs.'),
        tf('Le teaser mentionne généralement le nom de la société à vendre.', false, 'Le teaser est anonyme (nom de code) pour préserver la confidentialité jusqu’à la signature du NDA.'),
        mcq('Ordre de grandeur de la taille d’un Information Memorandum :', ['1 à 2 pages', '50 à 100 pages', '500 pages', '10 slides'], 1, 'L’IM est un document complet de présentation, typiquement 50 à 100 pages.'),
        mcq('Dans une LOI, quelles clauses sont généralement engageantes ?', ['Le prix', 'La confidentialité et l’exclusivité', 'Toutes', 'Aucune'], 1, 'La LOI n’oblige pas à conclure, mais l’exclusivité et la confidentialité qu’elle contient sont, elles, engageantes.'),
        mcq('Clause du NDA qui interdit de débaucher les salariés de la cible :', ['Standstill', 'Non-sollicitation', 'Drag-along', 'MAC'], 1, 'La non-sollicitation protège le vendeur contre le pillage de ses talents par des acheteurs ayant eu accès à l’organigramme.'),
        open('Quelle est la différence entre un teaser et un Information Memorandum ?', `Le teaser est un document court (1 à 3 pages) et anonyme, envoyé avant le NDA pour susciter l'intérêt : activité, chiffres clés, points forts. L'IM est un document détaillé (50 à 100 pages) envoyé après signature du NDA : présentation complète de la société, du marché, du management, des états financiers historiques et du business plan. Le teaser sert à filtrer, l'IM sert à permettre une offre indicative.`, ['Taille : 1 à 3 pages vs 50 à 100', 'Anonyme vs nominatif', 'Avant vs après NDA', 'Contenu de l’IM : marché, management, financiers, BP', 'Objectif de chacun']),
      ]
    },
    {
      id: 'u2l3', title: 'Le SPA et la mécanique de prix',
      cards: [
        ['Le SPA', `Le <b>Share Purchase Agreement</b> (contrat de cession d'actions, ou SPA) est le contrat définitif. Il contient : prix et mécanisme d'ajustement, conditions suspensives, déclarations et garanties, indemnisation, engagements entre signing et closing, clauses de non-concurrence.`],
        ['Locked box', `Le prix est fixé sur la base d'un <b>bilan de référence</b> arrêté avant la signature (la « locked box date »). Après cette date, aucune valeur ne doit sortir vers le vendeur : c'est l'interdiction des <b>leakages</b> (dividendes, frais de management…). Le vendeur est souvent rémunéré par un <b>ticking fee</b> jusqu'au closing.<br>→ Certitude du prix : <b>plutôt favorable au vendeur</b>.`],
        ['Completion accounts', `Un prix provisoire est fixé à la signature, puis <b>ajusté après le closing</b> sur la dette nette et le BFR <b>réels</b> à la date de closing (comparés à un BFR normatif).<br>→ L'acheteur paie ce qu'il reçoit réellement : <b>plutôt favorable à l'acheteur</b>, mais source de litiges post-closing.`],
        ['Earn-out, escrow, crédit vendeur', `<ul><li><b>Earn-out</b> : complément de prix conditionné aux performances futures. Il rapproche les attentes divergentes de l'acheteur et du vendeur.</li><li><b>Escrow / séquestre</b> : une partie du prix est bloquée pour garantir les indemnisations éventuelles.</li><li><b>Crédit vendeur</b> (vendor loan) : le vendeur finance une partie du prix.</li><li><b>Réinvestissement</b> : le vendeur réinvestit une partie du produit de cession (fréquent en LBO).</li></ul>`],
        ['Garanties et MAC', `<ul><li><b>Representations & warranties</b> (déclarations et garanties) : le vendeur certifie des faits (comptes, contentieux, conformité).</li><li><b>Indemnités / GAP</b> (garantie d'actif et de passif) : le vendeur indemnise si un passif antérieur apparaît, avec franchises, seuils et plafonds.</li><li><b>Assurance W&I</b> : une assurance couvre les garanties, ce qui permet un « clean exit » au vendeur (fréquent quand le vendeur est un fonds).</li><li><b>MAC / MAE</b> : clause permettant à l'acheteur de se retirer si un événement défavorable significatif survient entre signing et closing.</li></ul>`]
      ],
      qs: [
        mcq('Quel mécanisme de prix est généralement favorable au vendeur ?', ['Completion accounts', 'Locked box', 'Earn-out', 'Escrow'], 1, 'Le prix est fixé et certain dès la signature ; le risque économique est transféré à l’acheteur à la date de la locked box.'),
        mcq('Dans une locked box, un dividende versé au vendeur après la date de référence est :', ['Autorisé', 'Un leakage interdit (sauf permitted leakage)', 'Un earn-out', 'Une condition suspensive'], 1, 'Les leakages sont interdits et remboursés euro pour euro, sauf ceux explicitement listés comme autorisés (permitted leakages).'),
        mcq('Quel outil permet de rapprocher un vendeur optimiste et un acheteur prudent sur le business plan ?', ['Le standstill', 'L’earn-out', 'Le NDA', 'La MAC'], 1, 'L’earn-out conditionne une partie du prix à l’atteinte d’objectifs : le vendeur est payé s’il a raison.'),
        tf('Une assurance W&I permet notamment à un fonds vendeur de sortir sans garantie résiduelle importante.', true, 'L’acheteur se retourne contre l’assureur plutôt que contre le vendeur : c’est le « clean exit ».'),
        mcq('Dans le mécanisme de completion accounts, le prix est ajusté sur :', ['Le cours de bourse', 'La dette nette et le BFR réels au closing', 'Le chiffre d’affaires de l’année suivante', 'Le taux d’intérêt'], 1, 'Le prix provisoire est ajusté sur les comptes de closing : dette nette réelle et écart de BFR par rapport au normatif.'),
        num('Prix de l’equity estimé à la signature : 500 M€, sur la base d’une dette nette de 100 M€ et d’un BFR normatif de 60 M€. Au closing : dette nette réelle 110 M€, BFR réel 70 M€. Prix final en completion accounts (M€) ?', 500, 0, 'M€', 'EV implicite = 600. Prix = 600 − dette nette réelle 110 + (BFR réel 70 − normatif 60) = 600 − 110 + 10 = 500 M€. La hausse de dette est compensée par un BFR plus élevé.'),
        mcq('À quoi sert un escrow ?', ['Financer l’acheteur', 'Bloquer une partie du prix pour garantir d’éventuelles indemnisations', 'Payer les conseils', 'Rémunérer le management'], 1, 'Le séquestre sécurise le recouvrement des indemnisations de l’acheteur au titre des garanties.'),
        open('Explique la différence entre locked box et completion accounts.', `Locked box : le prix est fixé sur un bilan de référence antérieur à la signature. Le risque et les flux sont transférés à l'acheteur à cette date ; aucune sortie de valeur vers le vendeur n'est permise (leakage) sauf exceptions listées, et le vendeur perçoit souvent un ticking fee. Avantage : certitude du prix, pas de litige post-closing, plutôt favorable au vendeur. Completion accounts : prix provisoire ajusté après le closing selon la dette nette et le BFR réels au closing (vs normatif). L'acheteur paie ce qu'il reçoit réellement, mais le process est plus long et source de litiges : plutôt favorable à l'acheteur.`, ['Locked box : prix fixé sur bilan de référence', 'Notion de leakage', 'Ticking fee', 'Completion accounts : ajustement dette nette et BFR au closing', 'Qui est favorisé (vendeur vs acheteur)']),
        open('Qu’est-ce qu’un earn-out et quels en sont les risques ?', `Un earn-out est un complément de prix versé au vendeur si la cible atteint des objectifs futurs (EBITDA, chiffre d'affaires, jalons). Il permet de combler un écart de valorisation et de garder un vendeur-dirigeant motivé. Risques : litiges sur le calcul et la définition des agrégats, conflit d'intérêts si l'acheteur pilote la société (il peut freiner l'atteinte des objectifs), complexité d'intégration car il faut isoler la performance de la cible.`, ['Complément de prix conditionnel', 'Combler l’écart de valorisation', 'Retenir le vendeur-dirigeant', 'Risque de litiges sur les définitions', 'Conflit avec l’intégration']),
      ]
    },
    {
      id: 'u2l4', title: 'Du signing au closing',
      cards: [
        ['Signing ≠ closing', `<b>Signing</b> : les parties signent le SPA et s'engagent.<br><b>Closing</b> : transfert effectif des titres contre paiement, une fois les <b>conditions suspensives</b> (CPs) levées. L'écart peut aller de quelques jours à plus d'un an pour les gros deals soumis à la concurrence.`],
        ['Les conditions suspensives', `<ul><li><b>Contrôle des concentrations</b> : Commission européenne ou autorités nationales (en France : l'Autorité de la concurrence) selon les seuils de chiffre d'affaires.</li><li><b>Contrôle des investissements étrangers</b> dans les secteurs sensibles (en France : autorisation du ministère de l'Économie).</li><li>Autorisations réglementaires sectorielles (banque, assurance, télécoms).</li><li>Accords de tiers (clauses de changement de contrôle).</li></ul>`],
        ['Entre signing et closing', `Le vendeur s'engage à gérer la société « en bon père de famille » (<b>ordinary course of business</b>) : pas de décision majeure sans accord de l'acheteur. L'acheteur prépare l'<b>intégration</b> (plan des 100 jours), sans pouvoir prendre le contrôle avant l'autorisation (interdiction du <b>gun jumping</b>).`],
        ['Certain funds', `En Europe, les vendeurs exigent que le financement de l'acheteur soit <b>certain</b> (« certain funds ») : pas de condition de financement dans le SPA. Les banques signent donc des engagements fermes dès la remise de l'offre ferme.`]
      ],
      qs: [
        tf('Le transfert de propriété des titres a lieu au signing.', false, 'Le transfert a lieu au closing, après levée des conditions suspensives. Le signing crée l’engagement contractuel.'),
        mcq('Qu’est-ce que le « gun jumping » ?', ['Lancer une OPA hostile', 'Prendre le contrôle opérationnel de la cible avant l’autorisation de concurrence', 'Fuiter l’information', 'Remettre une offre en retard'], 1, 'Les autorités de concurrence sanctionnent la prise de contrôle anticipée (par exemple, dicter les prix de la cible avant l’autorisation).'),
        mcq('Que signifie « certain funds » ?', ['Le prix est payé en cash', 'Le financement de l’acheteur est garanti, sans condition de financement', 'Le prix est fixé en locked box', 'Les fonds sont séquestrés'], 1, 'Le vendeur ne prend pas de risque de financement : les prêteurs s’engagent fermement.'),
        mcq('Laquelle n’est PAS une condition suspensive classique ?', ['Autorisation de concurrence', 'Autorisation des investissements étrangers', 'Atteinte du budget de l’année suivante', 'Autorisation d’un régulateur sectoriel'], 2, 'Une condition liée à la performance future serait trop incertaine : on traite ce sujet via un earn-out, pas via une CP.'),
        ord('Remets dans l’ordre :', ['Offre ferme', 'Exclusivité', 'Signing du SPA', 'Levée des conditions suspensives', 'Closing', 'Ajustement de prix post-closing']),
        open('Qu’est-ce qu’une clause MAC et pourquoi est-elle sensible ?', `La clause MAC (Material Adverse Change) permet à l'acheteur de ne pas finaliser l'opération si un événement défavorable significatif affecte la cible entre le signing et le closing. Elle est sensible car elle reporte le risque sur le vendeur : les vendeurs cherchent à la limiter (exclusions pour les événements de marché, macroéconomiques ou sectoriels), voire à l'exclure (fréquent en Europe). Les tribunaux l'interprètent strictement : l'événement doit être durable et significatif.`, ['Définition : événement défavorable entre signing et closing', 'Droit de retrait de l’acheteur', 'Répartition du risque', 'Exclusions (macro, secteur)', 'Interprétation stricte']),
      ]
    }
  ]
});
