MA.unit({
  id: 'u9', title: 'Fit & motivation', icon: '🎯',
  desc: 'Pitch, « pourquoi le M&A », questions comportementales, culture deal',
  lessons: [
    {
      id: 'u9l1', title: 'Le pitch : « Walk me through your CV »',
      cards: [
        ['L’enjeu', `C'est presque toujours la <b>première question</b>. Elle donne le ton. Objectif : <b>90 secondes à 2 minutes</b>, une histoire cohérente qui mène logiquement au poste.`],
        ['La structure', `<ol><li><b>Accroche</b> : qui tu es en une phrase.</li><li><b>Parcours</b> : formation et expériences, en insistant sur les <b>choix</b> et ce que tu en as appris (pas une liste).</li><li><b>Le déclic</b> : ce qui t'a amené vers le M&A.</li><li><b>Aujourd'hui</b> : pourquoi ce poste, dans cette banque, maintenant.</li></ol>`],
        ['Les erreurs classiques', `<ul><li>Réciter le CV ligne par ligne.</li><li>Trop long (plus de 3 minutes).</li><li>Aucun fil conducteur.</li><li>Pas de lien avec le poste visé.</li><li>Négatif sur un ancien employeur.</li></ul>`],
        ['Valoriser une expérience post-trade', `Un passage en <b>securities services</b> (conservation, post-marché, actifs numériques) est un atout à présenter comme tel : compréhension de l'infrastructure des marchés et des contraintes des clients institutionnels, rigueur opérationnelle, exposition aux sujets de transformation (T+1, tokenisation) qui sont aussi des thèmes de M&A (consolidation des infrastructures de marché, acquisitions dans la fintech). Le déclic : passer de l'exécution des flux à la <b>décision stratégique</b> et à la valorisation.`]
      ],
      qs: [
        mcq('Durée idéale pour « walk me through your CV » :', ['20 secondes', '1 min 30 à 2 min', '5 à 7 minutes', 'Aussi long que nécessaire'], 1, 'Assez pour raconter une histoire, assez court pour laisser le recruteur rebondir.'),
        ord('Remets la structure du pitch dans l’ordre :', ['Accroche (qui tu es)', 'Parcours et choix', 'Le déclic vers le M&A', 'Pourquoi ce poste, maintenant']),
        mcq('Quelle est la meilleure façon de présenter tes expériences ?', ['Liste exhaustive des tâches', 'Les choix faits et ce que tu en as appris, en lien avec le M&A', 'Uniquement les notes obtenues', 'Ce que tu n’as pas aimé'], 1, 'Le recruteur cherche une logique de parcours et des compétences transférables.'),
        open('Walk me through your CV.', `Structure en 4 temps, 2 minutes maximum. Accroche : une phrase sur qui tu es (formation, spécialité). Parcours : chaque étape présentée comme un choix, avec ce qu'elle t'a apporté de concret et transférable (rigueur, modélisation, compréhension des marchés et des clients institutionnels). Le déclic : le moment où tu as compris que tu voulais travailler sur les décisions stratégiques et la valorisation (un deal suivi, un cours, une discussion). Aujourd'hui : pourquoi le M&A, pourquoi cette maison (secteurs, taille de deals, culture), pourquoi maintenant. Finir sur une phrase qui ouvre la discussion.`, ['Accroche en 1 phrase', 'Expériences = choix + apprentissages', 'Compétences transférables chiffrées', 'Déclic vers le M&A', 'Lien avec la banque visée', 'Moins de 2 à 3 minutes']),
        open('Tu viens du post-trade / securities services : pourquoi passer au M&A ?', `Partir du positif : le post-trade m'a donné une compréhension concrète de l'infrastructure des marchés, des contraintes des investisseurs institutionnels et des chantiers de transformation (T+1, actifs numériques). J'y ai développé rigueur, précision et capacité à gérer des volumes sous contrainte de délai, qui sont essentielles en M&A. Mais j'ai envie de passer de l'exécution des flux à la décision : comprendre pourquoi une entreprise se vend ou achète, la valoriser, construire l'equity story. Le déclic : un sujet ou deal concret observé (consolidation d'infrastructures de marché, rapprochements dans les services titres). Ce n'est pas une fuite, c'est une continuité : je comprends un secteur que beaucoup de candidats ne connaissent que de l'extérieur.`, ['Valoriser l’expérience (pas de fuite)', 'Compétences transférables : rigueur, volume, délais', 'Envie de stratégie et de valorisation', 'Exemple concret de déclic', 'Atout sectoriel (FIG, infrastructures de marché)']),
      ]
    },
    {
      id: 'u9l2', title: 'Pourquoi le M&A, pourquoi nous',
      cards: [
        ['« Pourquoi le M&A ? »', `Trois piliers :<ol><li><b>Le contenu</b> : décisions stratégiques majeures, variété des secteurs, rigueur technique (modélisation, valorisation).</li><li><b>L'apprentissage</b> : courbe d'apprentissage très rapide, exposition aux dirigeants.</li><li><b>Le concret</b> : un deal a un début et une fin, un impact réel sur des entreprises.</li></ol>Appuie chaque pilier sur une <b>expérience personnelle</b>. Évite « l'argent » et « le prestige ».`],
        ['« Pourquoi notre banque ? »', `Montre que tu as fait tes recherches : <b>positionnement</b> (bulge bracket, boutique, mid-cap), <b>secteurs forts</b>, <b>deals récents</b> (cite-en un ou deux que tu peux analyser), <b>taille des équipes</b> (plus de responsabilités dans une petite équipe), <b>personnes rencontrées</b> (afterworks, anciens). Une réponse qui marcherait pour toutes les banques est une mauvaise réponse.`],
        ['Connaître les métiers voisins', `<ul><li><b>ECM / DCM</b> : levées de fonds en actions / en dette.</li><li><b>Leveraged finance</b> : dette d'acquisition.</li><li><b>Transaction Services</b> : due diligence financière.</li><li><b>Private equity</b> : côté investisseur, horizon long, on vit avec les participations.</li><li><b>Corporate development</b> : M&A en interne chez un industriel.</li></ul>`],
        ['La question « et après ? »', `« Où te vois-tu dans 5 ans ? » : montre de l'ambition <b>dans le métier</b> (associate, prise de responsabilités, spécialisation sectorielle). Évoquer le PE est possible mais délicat : ne donne pas l'impression que la banque n'est qu'un tremplin.`]
      ],
      qs: [
        mcq('Quelle réponse à « Pourquoi le M&A ? » est la plus faible ?', ['La courbe d’apprentissage et la technicité', 'L’impact stratégique des opérations', 'La rémunération et le prestige', 'La variété des secteurs et des problématiques'], 2, 'Même si c’est une réalité, c’est la réponse qui convainc le moins un recruteur.'),
        mcq('Quelle est la différence principale entre M&A et ECM ?', ['ECM conseille sur les fusions, M&A sur les IPO', 'M&A conseille sur les acquisitions/cessions, ECM sur les levées en actions (IPO, augmentations de capital)', 'Aucune', 'ECM ne concerne que la dette'], 1, 'ECM = Equity Capital Markets : IPO, augmentations de capital, placements accélérés.'),
        tf('Une bonne réponse à « Pourquoi notre banque ? » peut s’appliquer à n’importe quelle banque.', false, 'Elle doit être spécifique : deals récents, secteurs, positionnement, personnes rencontrées.'),
        mcq('Différence entre banquier M&A et investisseur en PE ?', ['Aucune', 'Le banquier conseille sur une transaction ; l’investisseur PE prend des participations et les gère sur plusieurs années', 'Le PE ne fait pas de valorisation', 'Le banquier investit son propre argent'], 1, 'Le conseil est rémunéré par des honoraires sur le deal ; le PE vise un rendement sur le capital investi et accompagne la participation.'),
        open('Pourquoi le M&A ?', `Trois raisons, chacune illustrée. 1) Le contenu : participer à des décisions qui transforment une entreprise, avec une forte exigence technique (valorisation, modélisation, structuration) ; exemple d'un cours, d'un stage ou d'un deal qui t'a marqué. 2) L'apprentissage : une courbe très rapide, la variété des secteurs et l'exposition à des dirigeants dès le début. 3) Le côté concret et collectif : un deal a un début, une fin, un résultat ; travailler en équipe sous pression m'a plu dans telle expérience. Montrer qu'on connaît la réalité du métier (horaires, exigence) et qu'on l'a choisie en connaissance de cause.`, ['Contenu stratégique et technique', 'Courbe d’apprentissage', 'Concret / travail d’équipe', 'Chaque point illustré par une expérience', 'Lucidité sur le rythme', 'Pas d’argent / prestige en argument']),
        open('Pourquoi notre banque plutôt qu’une autre ?', `Réponse en 3 temps et spécifique. 1) Positionnement : ce qui distingue la maison (boutique indépendante et absence de conflits d'intérêts, ou plateforme intégrée avec financement, ou spécialiste mid-cap avec des équipes réduites et donc plus de responsabilités). 2) Deals et secteurs : un ou deux deals récents que tu as étudiés et dont tu peux expliquer la logique, des secteurs forts qui t'intéressent. 3) Les gens : rencontres (forums, afterworks, anciens de ton école) et ce qu'elles t'ont appris de la culture. Conclure sur ce que tu peux apporter.`, ['Positionnement spécifique de la banque', 'Deals récents étudiés', 'Secteurs d’expertise', 'Rencontres / culture', 'Ce que j’apporte']),
        open('Où te vois-tu dans 5 ans ?', `Montrer de l'ambition dans le métier et de la cohérence : avoir progressé d'analyste à associate, maîtriser l'exécution de bout en bout, avoir développé une expertise sectorielle, commencer à encadrer des juniors et à être en contact direct avec les clients. Rester ouvert sans présenter la banque comme un tremplin vers autre chose.`, ['Progression dans le métier (associate)', 'Expertise sectorielle', 'Encadrement / relation client', 'Pas de « tremplin »']),
      ]
    },
    {
      id: 'u9l3', title: 'Questions comportementales',
      cards: [
        ['La méthode STAR', `<b>S</b>ituation : le contexte en une phrase.<br><b>T</b>âche : ton rôle, l'objectif.<br><b>A</b>ction : ce que <b>toi</b> tu as fait (dis « je », pas « on »).<br><b>R</b>ésultat : chiffré si possible, et ce que tu as appris.`],
        ['Prépare 5 histoires', `Prépare 5 histoires réutilisables qui couvrent : <b>leadership</b>, <b>travail d'équipe et conflit</b>, <b>échec</b>, <b>pression et délais</b>, <b>erreur et rigueur</b>. Une même histoire peut servir plusieurs questions.`],
        ['Forces et faiblesses', `<b>Force</b> : utile en M&A (rigueur, capacité de travail, esprit de synthèse), prouvée par un exemple.<br><b>Faiblesse</b> : réelle mais non rédhibitoire, avec ce que tu fais pour la corriger. À éviter : « je suis perfectionniste » sans plus, ou une faiblesse incompatible (« je déteste Excel »).`],
        ['L’échec', `Choisis un vrai échec, assume-le sans te victimiser, et insiste sur <b>ce que tu as appris</b> et <b>ce que tu fais différemment</b> depuis. C'est la maturité qui est évaluée.`]
      ],
      qs: [
        ord('Remets la méthode STAR dans l’ordre :', ['Situation', 'Tâche', 'Action', 'Résultat']),
        mcq('Dans la partie « Action » de STAR, il faut :', ['Parler de l’équipe en « on »', 'Décrire ce que TOI tu as fait, en « je »', 'Décrire le contexte', 'Donner le résultat'], 1, 'Le recruteur évalue ta contribution personnelle.'),
        mcq('Quelle faiblesse est à éviter ?', ['« J’ai tendance à vouloir tout faire moi-même, j’apprends à déléguer »', '« Je n’aime pas le travail minutieux sur les chiffres »', '« Je manquais d’aisance à l’oral, j’ai rejoint une association de débat »', '« J’ai du mal à dire non, je priorise mieux maintenant »'], 1, 'La rigueur sur les chiffres est le cœur du métier d’analyste : faiblesse rédhibitoire.'),
        tf('Pour la question sur un échec, il vaut mieux choisir un faux échec qui est en réalité une réussite.', false, 'Les recruteurs repèrent ces réponses. Un vrai échec assumé, avec les leçons tirées, montre de la maturité.'),
        open('Parle-moi d’une fois où tu as travaillé sous une forte pression.', `Méthode STAR. Situation : contexte précis (projet, stage, association) avec une contrainte de délai forte. Tâche : ton rôle et l'enjeu. Action : comment tu as priorisé (urgent vs important), découpé le travail, communiqué avec l'équipe ou le manager sur l'avancement et les risques, gardé la qualité (double vérification des chiffres). Résultat : livrable rendu à temps, chiffré si possible, et ce que tu en as tiré (méthode de priorisation réutilisée depuis). Lien avec le M&A : délais serrés et exigence de zéro erreur.`, ['STAR complet', 'Priorisation', 'Communication avec le manager / l’équipe', 'Maintien de la qualité', 'Résultat et leçon', 'Lien avec le métier']),
        open('Quelle est ta plus grande faiblesse ?', `Choisir une faiblesse réelle, non rédhibitoire pour un analyste, et montrer le plan d'action. Exemple : « J'avais tendance à vouloir tout vérifier moi-même et à avoir du mal à déléguer ou à demander de l'aide, ce qui me faisait perdre du temps. En stage, j'ai appris à poser mes questions plus tôt, groupées, et à valider le format attendu avant de me lancer. » Être bref, sincère, et finir sur le progrès.`, ['Faiblesse réelle', 'Non rédhibitoire pour le poste', 'Exemple concret', 'Plan d’action', 'Progrès constaté']),
        open('Parle-moi d’un échec.', `Un vrai échec, avec une part de responsabilité personnelle, présenté en STAR : contexte, ce qui n'a pas marché, ta part de responsabilité sans accuser les autres, ce que tu as fait pour limiter les dégâts, et surtout ce que tu as appris et appliqué ensuite (exemple d'une situation ultérieure où tu as fait mieux). Ton posé, pas de dramatisation.`, ['Vrai échec, responsabilité assumée', 'Pas de reproche aux autres', 'Réaction immédiate', 'Leçon tirée', 'Application ultérieure']),
        open('Parle-moi d’un désaccord avec un membre de ton équipe.', `STAR : contexte précis et nature du désaccord (sur le fond, pas sur une personne). Action : j'ai écouté ses arguments, recherché les faits et les données, proposé une solution ou un compromis et, si besoin, escaladé de manière constructive. Résultat : décision prise, relation préservée, et ce que j'en ai retenu (désaccord exprimé tôt et factuellement). En M&A, savoir challenger un chiffre poliment est une qualité.`, ['Désaccord sur le fond', 'Écoute et faits', 'Solution / compromis', 'Relation préservée', 'Leçon']),
      ]
    },
    {
      id: 'u9l4', title: 'Culture deal et fin d’entretien',
      cards: [
        ['« Parle-moi d’un deal récent »', `Question quasi systématique. Prépare <b>2 à 3 deals</b> (un grand deal médiatisé, un deal du secteur de la banque, idéalement un deal sur lequel la banque a conseillé). Structure :<ol><li>Les <b>parties</b>, le <b>montant</b>, le <b>multiple</b>.</li><li>La <b>logique stratégique</b>.</li><li>Le <b>financement</b> et la structure.</li><li>Ton <b>avis</b> : bon deal ou pas, risques.</li></ol>`],
        ['Suivre l’actualité', `Lis chaque jour les rubriques deals de la presse financière (Les Échos, Financial Times, l'Agefi) et des newsletters M&A. Note dans un carnet : parties, montant, multiple, conseils, logique. Et fais le lien avec les <b>taux d'intérêt</b>, qui conditionnent les volumes de LBO et les valorisations.`],
        ['« As-tu des questions ? »', `Ne jamais répondre non. Bonnes questions : le staffing (secteurs, généraliste ou spécialisé), la place donnée aux analystes sur les deals, un deal récent de l'équipe, le parcours du recruteur, ce qui distingue les meilleurs analystes. À éviter : salaire, vacances et horaires au premier tour, et tout ce qui est sur le site.`],
        ['Le jour J', `Arrive en avance, connais le nom de tes interlocuteurs, aie ton CV en tête dans le détail (tout ce qui y est écrit peut être questionné), parle chiffres. Si tu ne sais pas une réponse technique : raisonne à voix haute, ne bluffe jamais.`]
      ],
      qs: [
        ord('Structure pour présenter un deal :', ['Parties, montant et multiple', 'Logique stratégique', 'Financement et structure', 'Ton avis et les risques']),
        mcq('À la question « As-tu des questions ? », quelle réponse est la meilleure ?', ['« Non, tout est clair »', '« Quel est le salaire ? »', '« Comment les analystes sont-ils staffés et quelle place ont-ils dans la relation client ? »', '« Combien de jours de vacances ? »'], 2, 'Une question sur le fonctionnement concret montre ton intérêt pour le métier.'),
        tf('Face à une question technique dont tu ne connais pas la réponse, il vaut mieux bluffer avec assurance.', false, 'Raisonne à voix haute à partir des principes : c’est ce qui est évalué. Le bluff est vite repéré et fatal.'),
        mcq('Pourquoi les taux d’intérêt influencent-ils l’activité M&A ?', ['Ils n’ont aucun impact', 'Ils déterminent le coût de la dette d’acquisition et les taux d’actualisation, donc les volumes de LBO et les valorisations', 'Ils fixent le prix des actions', 'Ils sont fixés par l’AMF'], 1, 'Des taux plus élevés renchérissent la dette (moins de levier possible en LBO) et augmentent le WACC (valorisations plus basses).'),
        open('Parle-moi d’un deal récent qui t’a intéressé.', `Structure : 1) les parties, le montant, le multiple implicite (EV/EBITDA) et la prime si cible cotée ; 2) la logique stratégique (consolidation, intégration verticale, diversification, technologie) et les synergies annoncées ; 3) la structure : cash ou titres, financement (dette, augmentation de capital), autorisations nécessaires (concurrence, investissements étrangers) ; 4) ton avis argumenté : prix justifié ou non au regard des synergies, risques d'exécution et d'intégration, réaction du marché (cours de l'acheteur à l'annonce). Choisir un deal que tu maîtrises sur le bout des doigts, idéalement dans un secteur de la banque.`, ['Parties, montant, multiple / prime', 'Logique stratégique et synergies', 'Mode de paiement et financement', 'Autorisations / calendrier', 'Avis argumenté et risques', 'Réaction du marché']),
        open('Comment évolue le marché du M&A en ce moment selon toi ?', `Structure de réponse, à mettre à jour avec l'actualité du jour : 1) le contexte macro (niveau des taux et anticipations des banques centrales, croissance, volatilité) et son effet sur le financement ; 2) les volumes et les tendances par segment : grands deals stratégiques, activité des fonds (stock de capitaux à investir et participations à céder), sorties via IPO ; 3) les thèmes sectoriels porteurs (technologie et IA, énergie et transition, santé, infrastructures) ; 4) les points d'attention (réglementation, contrôle des investissements étrangers, géopolitique). Citer un ou deux deals précis et récents à l'appui.`, ['Contexte macro et taux', 'Activité des fonds et stratégiques', 'Fenêtre IPO / sorties', 'Thèmes sectoriels', 'Risques réglementaires / géopolitiques', 'Exemples de deals récents']),
      ]
    }
  ]
});
