/* Simulations d'entretien : chaque série pioche au hasard dans les unités.
   src : [unité, types, nombre] */
MA.sims = [
  { id: 's1', title: 'Premier tour', icon: '☕', level: 'Débutant', desc: 'Fit, motivation et bases techniques, comme un premier entretien RH / analyste.', sec: 150,
    src: [['u9', ['open'], 3], ['u1', ['open'], 1], ['u4', ['open'], 1], ['u3', ['open'], 1], ['u4', ['num'], 2]] },
  { id: 's2', title: 'Technique : comptabilité', icon: '📒', level: 'Intermédiaire', desc: 'Les 3 états financiers et les walkthroughs, à l’oral et chiffrés.', sec: 120,
    src: [['u3', ['open'], 3], ['u3', ['num'], 4]] },
  { id: 's3', title: 'Technique : valorisation', icon: '📊', level: 'Intermédiaire', desc: 'EV, multiples, comparables, DCF : la base de tout entretien M&A.', sec: 150,
    src: [['u4', ['open'], 1], ['u5', ['open'], 2], ['u6', ['open'], 2], ['u6', ['num'], 2], ['u4', ['num'], 1]] },
  { id: 's4', title: 'Technique : LBO & structuration', icon: '🏦', level: 'Avancé', desc: 'LBO, TRI de tête, accretion / dilution, goodwill, process.', sec: 150,
    src: [['u7', ['open'], 2], ['u7', ['num'], 2], ['u8', ['open'], 2], ['u8', ['num'], 2], ['u2', ['open'], 1]] },
  { id: 's5', title: 'Superday', icon: '🔥', level: 'Final', desc: 'L’épreuve finale : 14 questions sur tout le programme, fit compris. C’est la simulation qui compte le plus pour ton feu vert.', sec: 150,
    src: [['u9', ['open'], 2], ['u2', ['open'], 1], ['u3', ['open'], 1], ['u3', ['num'], 1], ['u4', ['num'], 1], ['u5', ['open'], 1], ['u6', ['open'], 1], ['u6', ['num'], 1], ['u7', ['open'], 1], ['u7', ['num'], 1], ['u8', ['num'], 1], ['u8', ['open'], 1], ['u10', ['open'], 1]] },
  { id: 's6', title: 'Interview in English', icon: '🇬🇧', level: 'Intermédiaire', desc: 'Les grands classiques techniques et fit, en anglais.', sec: 150,
    src: [['u11', ['open'], 5]] },
];

MA.glossary = [
  ['Accretion / dilution', 'Accretion / dilution', 'Effet d’une acquisition sur le BPA de l’acheteur : hausse (relutif) ou baisse (dilutif).'],
  ['Actions diluées', 'Diluted shares', 'Actions existantes + actions potentielles dans la monnaie (options, BSA, convertibles), calculées via la TSM.'],
  ['ANR', 'NAV (Net Asset Value)', 'Actif net réévalué : valeur de marché des actifs moins les dettes. Holdings, foncières.'],
  ['Asset deal', 'Asset deal', 'Achat d’actifs sélectionnés plutôt que des titres de la société.'],
  ['Badwill', 'Bargain purchase', 'Goodwill négatif : prix inférieur à la juste valeur des actifs nets. Gain immédiat en résultat.'],
  ['Bêta', 'Beta', 'Sensibilité du rendement d’une action à celui du marché (risque systématique).'],
  ['BFR', 'Net working capital', 'Stocks + créances clients − dettes fournisseurs (et autres éléments d’exploitation).'],
  ['BPA', 'EPS', 'Bénéfice par action = résultat net / nombre d’actions.'],
  ['Build-up', 'Buy-and-build', 'Stratégie d’acquisitions successives autour d’une plateforme.'],
  ['CAPM / MEDAF', 'CAPM', 'Ke = Rf + β × (Rm − Rf).'],
  ['Carve-out', 'Carve-out', 'Cession d’une division d’un groupe.'],
  ['Certain funds', 'Certain funds', 'Financement garanti sans condition, exigé par les vendeurs en Europe.'],
  ['Closing', 'Closing', 'Transfert effectif des titres et paiement du prix, après levée des conditions suspensives.'],
  ['Completion accounts', 'Completion accounts', 'Prix ajusté après closing sur la dette nette et le BFR réels.'],
  ['Conditions suspensives', 'Conditions precedent (CPs)', 'Conditions à réunir avant le closing (concurrence, régulateurs…).'],
  ['Covenant', 'Covenant', 'Engagement financier imposé par les prêteurs (levier max, couverture des intérêts).'],
  ['Data room', 'Data room', 'Espace sécurisé regroupant les documents de due diligence.'],
  ['DCF', 'Discounted cash flow', 'Valorisation par actualisation des free cash-flows futurs.'],
  ['Dette nette', 'Net debt', 'Dettes financières − trésorerie et équivalents.'],
  ['Due diligence', 'Due diligence', 'Audit d’acquisition : financier, juridique, fiscal, commercial, ESG…'],
  ['Earn-out', 'Earn-out', 'Complément de prix conditionné aux performances futures de la cible.'],
  ['EBITDA', 'EBITDA', 'Résultat d’exploitation avant dotations aux amortissements et provisions.'],
  ['Enterprise Value', 'Enterprise value', 'Valeur de l’outil opérationnel pour tous les apporteurs de capitaux.'],
  ['Equity Value', 'Equity value', 'Valeur revenant aux actionnaires (actions diluées × cours).'],
  ['Escrow / séquestre', 'Escrow', 'Partie du prix bloquée pour garantir d’éventuelles indemnisations.'],
  ['FCFF', 'Unlevered free cash flow', 'EBIT × (1 − t) + D&A − capex − ΔBFR.'],
  ['Football field', 'Football field', 'Graphique de synthèse des fourchettes de valeur par méthode.'],
  ['GAP', 'Indemnity', 'Garantie d’actif et de passif : indemnisation de l’acheteur en cas de passif antérieur.'],
  ['Goodwill', 'Goodwill', 'Prix payé − juste valeur des actifs nets identifiables.'],
  ['IM', 'CIM / Information memorandum', 'Document détaillé de présentation de la cible envoyé après le NDA.'],
  ['Intérêts minoritaires', 'Non-controlling interests', 'Part des filiales consolidées détenue par des tiers.'],
  ['Leakage', 'Leakage', 'Sortie de valeur vers le vendeur après la date de locked box (interdite).'],
  ['LBO', 'Leveraged buy-out', 'Acquisition financée en grande partie par dette, remboursée par la cible.'],
  ['Levier', 'Leverage', 'Dette nette / EBITDA.'],
  ['Locked box', 'Locked box', 'Prix fixé sur un bilan de référence, sans ajustement post-closing.'],
  ['LTM / NTM', 'LTM / NTM', '12 derniers mois glissants / 12 prochains mois.'],
  ['MAC', 'Material adverse change', 'Clause de sortie en cas d’événement défavorable majeur entre signing et closing.'],
  ['Mezzanine', 'Mezzanine', 'Dette subordonnée, plus chère que la senior, souvent avec une part PIK.'],
  ['MOIC', 'MOIC', 'Multiple sur capital investi = valeur reçue / montant investi.'],
  ['NBO', 'Non-binding offer / IOI', 'Offre indicative non engageante de phase 1.'],
  ['NDA', 'NDA', 'Accord de confidentialité.'],
  ['OPA / OPE', 'Tender offer / exchange offer', 'Offre publique d’achat (cash) / d’échange (titres).'],
  ['P/E', 'P/E ratio', 'Cours / BPA, ou capitalisation / résultat net.'],
  ['PIK', 'Payment in kind', 'Intérêts capitalisés, payés à l’échéance.'],
  ['PPA', 'Purchase price allocation', 'Réévaluation à la juste valeur des actifs et passifs de la cible.'],
  ['Prime de contrôle', 'Control premium', 'Surcoût payé par rapport au cours pour obtenir le contrôle.'],
  ['Process letter', 'Process letter', 'Règles du process : calendrier, format des offres.'],
  ['Retrait obligatoire', 'Squeeze-out', 'Rachat forcé des minoritaires (≥ 90 % en France).'],
  ['SPA', 'Share purchase agreement', 'Contrat de cession des titres.'],
  ['Synergies', 'Synergies', 'Gains de coûts ou de revenus liés au rapprochement.'],
  ['Teaser', 'Teaser', 'Présentation anonyme de 1 à 3 pages de l’opportunité.'],
  ['TRI', 'IRR', 'Taux de rendement interne : taux qui annule la VAN des flux.'],
  ['TSM', 'Treasury stock method', 'Calcul de la dilution des options dans la monnaie.'],
  ['Unitranche', 'Unitranche', 'Dette in fine en une seule tranche, fournie par des fonds de dette privée.'],
  ['Valeur terminale', 'Terminal value', 'Valeur des flux au-delà de l’horizon explicite du DCF.'],
  ['VDD', 'Vendor due diligence', 'Due diligence commandée par le vendeur et partagée aux acheteurs.'],
  ['W&I', 'Warranty & indemnity insurance', 'Assurance couvrant les garanties du vendeur.'],
  ['WACC', 'WACC', 'Coût moyen pondéré du capital : E/(D+E) × Ke + D/(D+E) × Kd × (1 − t).'],
];
